# -*- coding: utf-8 -*-
"""Tribes Final Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRcWN_KF7kXzLBgugSmvIjL7WCKV8uTB
"""

# Import packages
import glob
import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt

from pathlib import Path

from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import SGD

from google.colab import drive

drive.mount('/content/gdrive')

filepath_tawu = "/content/gdrive/MyDrive/2 AI Dataset/雅美族(達悟族) Plan B/*"
filepath_taiya = "/content/gdrive/MyDrive/2 AI Dataset/泰雅族 (Plan B)/*"

tawu_files = [file for file in glob.iglob(filepath_tawu)]
taiya_files = [file for file in glob.iglob(filepath_taiya)]

tawu_files

taiya_files

#Create input(data) and output(target) dataset
#Label tawu as 1, and taiya as 0

data = []
target = []

for pa in range(len(tawu_files)):
    img = load_img(tawu_files[pa], target_size = (224, 224))
    x = np.array(img)
    data.append(x)
    target.append(1) #Tawu: Label 1

for pe in range(len(taiya_files)):
    img = load_img(taiya_files[pe], target_size = (224, 224))
    x = np.array(img)
    data.append(x)
    target.append(0) #Taiya: Label 0

from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

# Convert data and target to numpy arrays
data = np.array(data)
target = np.array(target)

# Normalize the images
data = data.astype('float32') / 255.0

# One-hot encode the labels
target = to_categorical(target, 2)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=42)

#creating the initial model using CNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.optimizers import SGD

# Define the model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(2, activation='softmax')
])

# Compile the model
model.compile(optimizer=SGD(learning_rate=0.01, momentum=0.9),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

#Transfer learning using ResNet50V2
from tensorflow.keras.applications import ResNet50V2
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model

# Load the ResNet50V2 model pre-trained on ImageNet, excluding the top layers
base_model = ResNet50V2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# Add custom top layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
predictions = Dense(2, activation='softmax')(x)

# Define the final model
model = Model(inputs=base_model.input, outputs=predictions)

# Freeze the layers of the base model
for layer in base_model.layers:
    layer.trainable = False

# Compile the model
model.compile(optimizer=SGD(learning_rate=0.001, momentum=0.9),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Unfreeze some layers of the base model for fine-tuning
for layer in base_model.layers[-10:]:
    layer.trainable = True

# Re-compile the model with a lower learning rate
model.compile(optimizer=SGD(learning_rate=0.0001, momentum=0.9),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Fine-tune the model
history_fine = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(f'Test accuracy: {test_acc}')

!pip install gradio==3.43.1

import gradio as gr

from tensorflow.keras.applications.resnet_v2 import preprocess_input

labels = ['Tawu', 'Taiya']

def classify_image(inp):
  inp = inp.reshape((-1, 224, 224, 3))
  inp = preprocess_input(inp)
  p = model.predict(inp).flatten()[0]
  return {'Tawu': float(1-p), 'Taiya': float(p)}

image = gr.inputs.Image(shape=(224, 224), label="Image of Tawu or Taiya")
label = gr.outputs.Label(label="AI Result")

gr.Interface(fn=classify_image, inputs=image, outputs=label,
             title="AI Tawu and Taiya Classifier",
             description="This classifier uses transfer learning to identify tawu or taiya"
             ).launch(debug=True)

model.save('/content/gdrive/MyDrive/Final Code/AI_final_model')

import tensorflow as tf
from tensorflow import keras

new_model = tf.keras.models.load_model('/content/gdrive/MyDrive/Final Code/AI_final_model')

new_model.summary()